### ISSUE TITLE
Admin Area Server Choose Issue

### ISSUE THREAD

**Issue by betaboy44** [GiovanniMounir/onlinenet-module#5]
We can't able to choose "none" in servers list it server belongs to other DC,..it automatically randomly choose any server itself.

![d](https://cloud.githubusercontent.com/assets/13134001/8958749/356dc54c-3624-11e5-8445-df89e0b88573.PNG)

**Comment by GiovanniMounir** [comment]
Hello, I'm not honestly certain whether the issue should be with the module or not, but I believe it's something to do with WHMCS itself as I couldn't notice any option I can integrate into the code to control the associated server, nor did I see anything like that on any of WHMCS documentations.

I'm putting the invalid label for now since it's something out of the module's control, but if it turns out that it isn't, please let me know and I'll try to implement a fix.
